// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKY8FzQTACeMXNRPD7LfBNkZQGGmTko5s',
    appId: '1:1081418837052:web:c8b24d3b2b168a499e6739',
    messagingSenderId: '1081418837052',
    projectId: 'assignment-f7101',
    authDomain: 'assignment-f7101.firebaseapp.com',
    storageBucket: 'assignment-f7101.appspot.com',
    measurementId: 'G-74WTF8DNYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1GTbLsflTuWQkVHoAlgDwlpNfLzDWIY',
    appId: '1:1081418837052:android:6e63aec1b03bf9089e6739',
    messagingSenderId: '1081418837052',
    projectId: 'assignment-f7101',
    storageBucket: 'assignment-f7101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bgu7hprlvGpBLyNifClK-geY4MxdCp8',
    appId: '1:1081418837052:ios:5c39d7b9ff7944da9e6739',
    messagingSenderId: '1081418837052',
    projectId: 'assignment-f7101',
    storageBucket: 'assignment-f7101.appspot.com',
    iosBundleId: 'com.example.digitalSalt',
  );
}
